### PR TITLE
Fix table comment updates

### LINKED ISSUE #732: Relation comments are not being updated for incremental models
### Describe the bug
Relation comments for incremental models are only persisted when the relation is first being created. On subsequent incremental runs an updated model description will not be persisted to the relation.

### Steps To Reproduce
1) Create an incremental model with:

`model.sql`
```sql
{{
    config(
        materialized="incremental",
        persist_docs={"relation": true},
    )
}}
select 1 as id
```
`schema.yml`
```yml
version: 2
models:
  - name: model
    description: "Model Description"
```
2) `dbt run`
3) Change the model description
4) `dbt run`
5) Check the table comment: `describe detail model`. The table still has the old model description as table comment.

### Expected behavior
After the second `dbt run` the new model description should be persisted as the table comment.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.3
  - latest:    1.8.3 - Up to date!

Plugins:
  - databricks: 1.8.3 - Up to date!
  - spark:      1.8.0 - Up to date!
```

**The operating system you're using:**
Ubuntu 22.04

**The output of `python --version`:**
Python 3.10.12

### Additional context
I'm interested in contributing to this.

### PR DESCRIPTION
**Pull request by henlue**
Resolves #732

### Description

 - Update table comments for incremental models on incremental runs
 - Update table comments for snapshots on incremental runs
 - Create table comments during dbt clone
 - Check for `config.persist_relation_docs()` in `persist_docs`
 - Align black versions in `black.ini` and `.pre-commit-config.yaml` to fix failing `pre-commit` runs

The issue is only about the incremental models. While working on the PR I realized table comments are also not being updated for snapshots and are not created with `dbt clone`.

I think comments are also not being updated in materialized views and streaming tables. Since I don't have a good understanding of those materializations, I kept the original behavior by setting `for_relation=False`. The tests would also run through with `for_relation=True`, but this might lead to unnecessary queries that are being send to databricks on the first run of those relations.

Generally, the code would be simpler if relation comments are only persisted in `persist_docs` (using `comment on ...` queries) and not as part of `create table` statements. I assume they are persisted as part of the `create` statement to improve performance?

I've ran:
`tox -e unit`
`tox -e integration-databricks-uc-sql-endpoint`
`tox -e integration-databricks-uc-cluster`

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

**Comment by benc-db** [comment]
> I think comments are also not being updated in materialized views and streaming tables. Since I don't have a good understanding of those materializations, I kept the original behavior by setting for_relation=False. The tests would also run through with for_relation=True, but this might lead to unnecessary queries that are being send to databricks on the first run of those relations.

They should already for MV/ST, but the mechanism is very different.  Look at alter.sql for either.  Core reason is that for MV/ST we have a mechanism for declaring how we want to handle changes (on_config_change), but I haven't convinced dbt-core yet that we should have the same mechanism for incremental tables.

**Comment by benc-db** [comment]
Basically, in the absence of on_config_change for other materialization types, you are assuming users want apply.  I think that is the correct assumption.  Thanks for PR, will review in the next day or so.

**Comment by benc-db** [comment]
Running functional tests now.

**Comment by benc-db** [comment]
Please take a look at the non-uc cluster tests; there are few that are failing.

**Comment by benc-db** [comment]
Rerunning functional tests

**Comment by henlue** [comment]
I forgot to sign my latest commit and had to force push it again.

**Comment by benc-db** [comment]
> I forgot to sign my latest commit and had to force push it again now.

Apologies for delay, I'm on-call and haven't had much time to review PRs.  Will get to this shortly.

**Comment by benc-db** [comment]
Does this by any chance fix: https://github.com/databricks/dbt-databricks/issues/763?

**Review by benc-db — DISMISSED** [review]

**Review by benc-db — APPROVED** [review]

**Comment by henlue** [comment]
> Does this by any chance fix: #763?

No that issue still persists

**Pull request merged**
