### PR TITLE
Cancel python models on Ctrl-C

### LINKED ISSUE #684: Python model doesn't have cancel method
### Describe the bug
We found that when a python model is canceled from terminal, it doesn't have a cancel method to cancel the job_cluster on Databricks. 

We think this could cause resource/cost waste and data error in some case.

### Steps To Reproduce
1.include a SQL model and a Python model in project.
2.execute them together.
3.use Control + C to exit the DBT execution.
4.you can see the SQL model on SQL warehouse has been canceled successfully, but Python Model on Job Cluster is still running. 
5.and the DBT execution will stuck until the Python model is finished.

### Expected behavior
All model should be canceled no matter SQL model or Python model.

### Screenshots and log output
image

### System information
image

**The operating system you're using:**

**The output of `python --version`:**

### PR DESCRIPTION
**Pull request by benc-db**
Resolves #684 

### Description

When you cancel a running dbt job, running SQL queries are cancelled.  This PR extends #690 to propagate the cancel behavior to python models.

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

**Comment by gaoshihang** [comment]
Hi @benc-db I have tested our scenario, everything runs smoothly, the python model can be canceled! Thank you very much!
image
image

It's very pleasure to work with you.

**Comment by gaoshihang** [comment]
Hi @benc-db Thanks for work on this. I still have a question, if we want to use this feature, which version should we use?

**Comment by benc-db** [comment]
> Hi @benc-db Thanks for work on this. I still have a question, if we want to use this feature, which version should we use?
Hasn't been released yet, will be part of 1.8.2.

**Comment by gaoshihang** [comment]
@benc-db Thanks!

**Pull request merged**
