### PR TITLE
Add optional argument for glob pattern in databricks COPY INTO

### PR DESCRIPTION
**Pull request by dluftspring**
### Description

This PR adds an optional key word argument to the `databricks_copy_into` macro that allows the user to specify a pattern for file globbing. Please let me know if there are unintended consequences i'm not considering but based on my reading of the docs this should work. Please let me know how you normally handle unit testing.

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

**Review by andrefurlan-db — APPROVED** [review]

**Review by allisonwang-db — APPROVED** [review]
Thanks for adding this!

**Comment by ueshin** [comment]
Hi @dluftspring, could you add an item in CHANGELOG? I'll backport this to 1.4, so the item would be under the section for 1.4.0. Thanks.

**Review by ueshin — APPROVED** [review]

**Comment by ueshin** [comment]
The linter failure is not related to this PR. Let's fix it later.

**Comment by ueshin** [comment]
Thanks! merging.

**Pull request merged**
