### PR TITLE
Lazy load agate

### PR DESCRIPTION
**Pull request by benc-db**
### Description

Replicates [629](https://github.com/databricks/dbt-databricks/pull/629) but on latest.  Also, I'm a little more aggressive about not instantiating Tables.

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

**Comment by benc-db** [comment]
@jackyhu-db goal is summarized in the other PR, but basically dbt Labs is pushing to delay loading the agate library as late as possible because it is heavy enough that loading it makes the cli load feel sluggish, and it's not needed until the first Table is created (at which point the user will generally not notice the time due to concurrency).  So, I've reduced my use of the Table class, and otherwise delayed loading until needed.

**Comment by jackyhu-db** [comment]
> @jackyhu-db goal is summarized in the other PR, but basically dbt Labs is pushing to delay loading the agate library as late as possible because it is heavy enough that loading it makes the cli load feel sluggish, and it's not needed until the first Table is created (at which point the user will generally not notice the time due to concurrency). So, I've reduced my use of the Table class, and otherwise delayed loading until needed.

Thanks @benc-db for adding this. Can we add some tests for this?

**Comment by benc-db** [comment]
> > @jackyhu-db goal is summarized in the other PR, but basically dbt Labs is pushing to delay loading the agate library as late as possible because it is heavy enough that loading it makes the cli load feel sluggish, and it's not needed until the first Table is created (at which point the user will generally not notice the time due to concurrency). So, I've reduced my use of the Table class, and otherwise delayed loading until needed.
> 
> Thanks @benc-db for adding this. Can we add some tests for this?

What did you have in mind?  The existing integration tests guard against regression, but are you thinking maybe unit tests against the methods I modified?

**Comment by jackyhu-db** [comment]
> > > @jackyhu-db goal is summarized in the other PR, but basically dbt Labs is pushing to delay loading the agate library as late as possible because it is heavy enough that loading it makes the cli load feel sluggish, and it's not needed until the first Table is created (at which point the user will generally not notice the time due to concurrency). So, I've reduced my use of the Table class, and otherwise delayed loading until needed.
> > 
> > 
> > Thanks @benc-db for adding this. Can we add some tests for this?
> 
> What did you have in mind? The existing integration tests guard against regression, but are you thinking maybe unit tests against the methods I modified?

That is good. Just wanted to make sure the change does not introduce regression. Adding the test case for the lazy load can be nice to have :-)

**Review by jackyhu-db — APPROVED** [review]

**Review by jackyhu-db — APPROVED** [review]

**Pull request merged**
