### PR TITLE
Add SQL Column Mismatch Validation Into Incremental Append Strategy

### PR DESCRIPTION
**Pull request by case-k-git**
Resolves #
https://github.com/databricks/dbt-databricks/issues/567

### Description
I have added validation to the append process of the incremental_strategy. This change will help when we add new columns into incremental append table.

If a new column is added to an existing dbt SQL and forgot to update dbx existing table columns, The query runs and succeeds, but the newly added columns in SQL are not added when using the incremental append strategy. Data will only be added to the old columns that exist in the existing table.

Since no error occurs, new column data will not be added despite the addition of columns to the SQL model, and subsequent dbt with dependencies will fail due to the lack of columns.

In this pull request , I have added validation to the append process of the incremental_strategy. If there is a shortage of columns, the process will now fail as follows.

To ensure idempotence in the append process, incremental append strategy created a temporary table with the new columns added, then narrowed down to the existing columns before adding data. It will be like this.The issue of this specification is data will be append without new columns and any error or warning message.

```
insert into table `catalog_demo`.`test17060086231712186480_Incremental_strategies`.`append_delta`
      select `id`, `msg` from `append_delta__dbt_tmp`
```
With this new revision, if there is a shortage of SQL columns, it will now be detectable along with the following error.In this example I add `msg2` column as a new one. We will be able to know new column is missing into dbx table because of the error. After checked this validation results, user can update exiting table column by executing ALTER TABLE manually.

```
insert into table `catalog_demo`.`test17060620400077328677_Incremental_strategies`.`append_delta`
      select `id`, `msg`, `msg2` from `append_delta__dbt_tmp`
```
```
  Table schema:
  root
  -- id: long (nullable = true)
  -- msg: string (nullable = true)
 
 
  Data schema:
  root
  -- id: long (nullable = true)
  -- msg: string (nullable = true)
  -- msg2: string (nullable = true)
 
           
  Table ACLs are enabled in this cluster, so automatic schema migration is not allowed. Please use the ALTER TABLE command for changing the schema.In this example I add msg2 column as a new one.
```

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

**Comment by benc-db** [comment]
Looking at the incremental tests, I'm wondering if the issue you're hitting is that you need to use a different setting for incremental schema changes.  Have you tried on_schema_change='fail'?

**Comment by case-k-git** [comment]
Ah I see I did not know that. Thank you for your review let me try tomorrow.
https://docs.getdbt.com/docs/build/incremental-models

**Comment by case-k-git** [comment]
@case-k-git  I confirmed thank you . let me close this PR

**Comment by case-k-git** [comment]
By the way do you if there are some option which can override default value from dbt project? if you know such a option appreciate if you let me know.

I created feature request to dbt core 
https://github.com/dbt-labs/dbt-core/issues/9449

**Comment by benc-db** [comment]
Does it not work to specify it like other model config in the project file?  https://docs.getdbt.com/reference/model-configs

**Comment by case-k-git** [comment]
Thank you for reply. I see it seems to be we can pass default option to apply each models. let me try this. Thank you!

**Comment by case-k-git** [comment]
It worked Thank you for reply and solution !!

**Pull request closed without merging**
